/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jframes;

import PreenchimentoTabelas.ModeloTabela;
import Tabela.Comanda;
import banco.ConectaBanco;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author home
 */
public class Tela_inserirComanda2 extends javax.swing.JFrame {
ConectaBanco conecta = new ConectaBanco();
String item, data, rua, cliente, tamanho,pastel, sabor1, sabor2, adicional, bebida, qtd_bebida, qtd_pastel, tipo ;
double total = 0, taxa= 0 , subtotal = 0, valor_item = 0 ;
DecimalFormat df = new DecimalFormat("##,###0.00"); 
Comanda pedido = new Comanda();
boolean entrega = false ;
    /**
     * Creates new form Tela_inserirComanda
     */
    public Tela_inserirComanda2()  {
        
        conecta.conexao();
        initComponents();
        combox1();
        del_list();
        jRadioButton_20cm.setSelected(true);
        jTextField_qtd2.setText("1");
        jTextField_qtd1.setText("1");
        
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_venda = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jTextField_nome = new javax.swing.JTextField();
        jTextField_ende = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton_entrega = new javax.swing.JRadioButton();
        jRadioButton_retirada = new javax.swing.JRadioButton();
        jTextField_id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jFormattedText_data = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jComboBox_sabor3 = new javax.swing.JComboBox<>();
        jComboBox_sabor4 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton_30cm = new javax.swing.JRadioButton();
        jRadioButton_20cm = new javax.swing.JRadioButton();
        jCheckBox_cheddar = new javax.swing.JCheckBox();
        jCheckBox_bacon = new javax.swing.JCheckBox();
        jCheckBox_catupiry = new javax.swing.JCheckBox();
        jCheckBox_tomate = new javax.swing.JCheckBox();
        jCheckBox_milho = new javax.swing.JCheckBox();
        jCheckBox_azeitona = new javax.swing.JCheckBox();
        jCheckBox_ovos = new javax.swing.JCheckBox();
        jButton_add_pastel1 = new javax.swing.JButton();
        jTextField_qtd2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jComboBox_bebida = new javax.swing.JComboBox<>();
        jTextField_qtd1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton_add_bebida1 = new javax.swing.JButton();
        jTextField_total = new javax.swing.JTextField();
        jButton_salvar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jComboBox_integral = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox_dividido1 = new javax.swing.JComboBox<>();
        jComboBox_dividido2 = new javax.swing.JComboBox<>();
        jComboBox_dividido3 = new javax.swing.JComboBox<>();
        jTextField_pag1 = new javax.swing.JTextField();
        jTextField_pag2 = new javax.swing.JTextField();
        jTextField_pag3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Knob Snapback_1.png"))); // NOI18N
        jButton1.setToolTipText("Voltar");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inserção de comandas");

        jTable_venda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable_venda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_venda.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jScrollPane4.setViewportView(jTable_venda);

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("data");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cliente");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("endereço");

        jRadioButton_entrega.setText("Entrega");
        jRadioButton_entrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_entregaActionPerformed(evt);
            }
        });

        jRadioButton_retirada.setText("Retirada");
        jRadioButton_retirada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_retiradaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("id pedido");

        try {
            jFormattedText_data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedText_data.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedText_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedText_dataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_ende, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jFormattedText_data, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_id)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton_retirada)
                    .addComponent(jRadioButton_entrega))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jFormattedText_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton_entrega))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_ende, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton_retirada))
                .addGap(20, 20, 20))
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "pastel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel8.setText("+");

        jRadioButton_30cm.setText("30 cm");
        jRadioButton_30cm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_30cmActionPerformed(evt);
            }
        });

        jRadioButton_20cm.setText("20 cm");
        jRadioButton_20cm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_20cmActionPerformed(evt);
            }
        });

        jCheckBox_cheddar.setText("cheddar");
        jCheckBox_cheddar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_cheddarActionPerformed(evt);
            }
        });

        jCheckBox_bacon.setText("Bacon");
        jCheckBox_bacon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_baconActionPerformed(evt);
            }
        });

        jCheckBox_catupiry.setText("catupiry");
        jCheckBox_catupiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_catupiryActionPerformed(evt);
            }
        });

        jCheckBox_tomate.setText("Tomate");
        jCheckBox_tomate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_tomateActionPerformed(evt);
            }
        });

        jCheckBox_milho.setText("Milho");
        jCheckBox_milho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_milhoActionPerformed(evt);
            }
        });

        jCheckBox_azeitona.setText("azeitona");
        jCheckBox_azeitona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_azeitonaActionPerformed(evt);
            }
        });

        jCheckBox_ovos.setText(" ovos    ");
        jCheckBox_ovos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_ovosActionPerformed(evt);
            }
        });

        jButton_add_pastel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jButton_add_pastel1.setText("adicionar");
        jButton_add_pastel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_add_pastel1ActionPerformed(evt);
            }
        });

        jTextField_qtd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_qtd2ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("quantidade");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton_30cm)
                            .addComponent(jRadioButton_20cm)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jComboBox_sabor3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox_sabor4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jCheckBox_milho, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBox_bacon)
                                    .addComponent(jTextField_qtd2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBox_ovos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBox_cheddar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(9, 9, 9)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jCheckBox_azeitona)
                                    .addComponent(jCheckBox_catupiry, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox_tomate, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_add_pastel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_20cm)
                    .addComponent(jComboBox_sabor3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_sabor4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton_30cm)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox_bacon)
                            .addComponent(jCheckBox_ovos)
                            .addComponent(jCheckBox_azeitona)
                            .addComponent(jCheckBox_tomate))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox_milho)
                            .addComponent(jCheckBox_cheddar)
                            .addComponent(jCheckBox_catupiry))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_add_pastel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_qtd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jPanel4.setBackground(new java.awt.Color(0, 153, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "bebidas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        jComboBox_bebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_bebidaActionPerformed(evt);
            }
        });

        jTextField_qtd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_qtd1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("quantidade");

        jButton_add_bebida1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jButton_add_bebida1.setText("adicionar");
        jButton_add_bebida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_add_bebida1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_add_bebida1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_qtd1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox_bebida, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jComboBox_bebida, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_qtd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jButton_add_bebida1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jTextField_total.setBackground(new java.awt.Color(2, 5, 5));
        jTextField_total.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jTextField_total.setForeground(new java.awt.Color(255, 153, 0));
        jTextField_total.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_total.setText("R$ 0.00");
        jTextField_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_totalActionPerformed(evt);
            }
        });

        jButton_salvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_salvar.setText("Salvar Comanda");
        jButton_salvar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salvarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Total");

        jPanel5.setBackground(new java.awt.Color(0, 153, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "forma de pagamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        jComboBox_integral.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "escolher", "Dinheiro", "Crédito", "Débito", "Pix", "PicPay" }));
      

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("integral");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("dividido");

        jComboBox_dividido1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "escolher", "Dinheiro", "Crédito", "Débito", "Pix", "PicPay" }));

        jComboBox_dividido2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "escolher", "Dinheiro", "Crédito", "Débito", "Pix", "PicPay" }));

        jComboBox_dividido3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "escolher", "Dinheiro", "Crédito", "Débito", "Pix", "PicPay" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_integral, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jComboBox_dividido3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_pag3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jComboBox_dividido2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_pag2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jComboBox_dividido1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_pag1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_integral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_dividido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_pag1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_dividido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_pag2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_dividido3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_pag3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(242, 242, 242)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(261, 261, 261))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(29, 29, 29)
                                .addComponent(jTextField_total, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(416, 416, 416)
                                            .addComponent(jLabel7))
                                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, 0))
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField_total, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 967, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_totalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Tela_inserirComanda estoque = new Tela_inserirComanda();
        // estoque.setLocationRelativeTo(null);
        // estoque.setVisible(true);
        // dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton_30cmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_30cmActionPerformed
        if (jRadioButton_30cm.isSelected())
          jRadioButton_20cm.setSelected(false);
    }//GEN-LAST:event_jRadioButton_30cmActionPerformed

    private void jRadioButton_20cmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_20cmActionPerformed
       if (jRadioButton_20cm.isSelected())
          jRadioButton_30cm.setSelected(false);
    }//GEN-LAST:event_jRadioButton_20cmActionPerformed

    private void jCheckBox_cheddarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_cheddarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_cheddarActionPerformed

    private void jCheckBox_baconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_baconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_baconActionPerformed

    private void jCheckBox_catupiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_catupiryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_catupiryActionPerformed

    private void jCheckBox_tomateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_tomateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_tomateActionPerformed

    private void jCheckBox_milhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_milhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_milhoActionPerformed

    private void jCheckBox_azeitonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_azeitonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_azeitonaActionPerformed

    private void jCheckBox_ovosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_ovosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_ovosActionPerformed

    private void jButton_add_pastel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_add_pastel1ActionPerformed
      if (jRadioButton_20cm.isSelected())
          tamanho = "20 cm" ;
      else 
          tamanho = "30 cm" ;
      
      if (jComboBox_sabor3.getSelectedIndex() == 0 && jComboBox_sabor4.getSelectedIndex() == 0 )
          JOptionPane.showMessageDialog(null,"escolha ao menos 1 sabor");
      else{
      if (jComboBox_sabor3.getSelectedIndex() > 0 && jComboBox_sabor4.getSelectedIndex() > 0)
          pastel = jComboBox_sabor3.getSelectedItem() +" & " + jComboBox_sabor4.getSelectedItem() ;
     
      if (jComboBox_sabor3.getSelectedIndex() == 0 && jComboBox_sabor4.getSelectedIndex() > 0)
          pastel = (String) jComboBox_sabor4.getSelectedItem();
      if (jComboBox_sabor3.getSelectedIndex() >= 0 && jComboBox_sabor4.getSelectedIndex() == 0)
          pastel = (String) jComboBox_sabor3.getSelectedItem();
      }

        String nome1, nome2;
        int index1 , index2;
        double item1=0, item2 ;
        index1 = jComboBox_sabor3.getSelectedIndex() ;
        index2 = jComboBox_sabor4.getSelectedIndex() ;
        
        nome1 = (String) jComboBox_sabor3.getSelectedItem() ;
        nome2 = (String) jComboBox_sabor4.getSelectedItem() ;
        
        if (index1 > 0 && index2 > 0){
            pesquisa_preco(nome1);
            item1 = valor_item ;
            pesquisa_preco((nome2));
            item2 = valor_item ;
            System.out.println("valor item1 "+item1);
            System.out.println("valor item2 "+item2);
            System.out.println("subtotal "+ subtotal);
            if(item1>item2){
                subtotal += item1 ;
                System.out.println("dentro if 1");
                System.out.println("subtotal= "+subtotal);
            }else
            if(item2>item1){
                subtotal += item2 ;
                System.out.println("dentro if 2");
            }
            else
                if (item1 == item2)
                    subtotal = item1;
            
        }else if (index2 > 0 && index1 == 0){
           item2 = pesquisa_preco(nome2);
           subtotal += valor_item;
        }else if (index1 > 0 && index2 ==0){
            pesquisa_preco(nome1);
            subtotal += valor_item;
        }
         if (jRadioButton_30cm.isSelected())
          subtotal += 3;
        System.out.println("30 cm sub="+subtotal);
     
        if (jCheckBox_bacon.isSelected()){
            pastel += " + bacon"; 
            subtotal+= 1 ;
        }
        if (jCheckBox_ovos.isSelected()){
            pastel += " + ovos";
            subtotal+= 1 ;
        }
        if (jCheckBox_azeitona.isSelected()){
            pastel += " + azeitona"; 
            subtotal+= 1 ;   
        }
        if (jCheckBox_milho.isSelected()){
            pastel += " + milho"; 
            
        }
        if (jCheckBox_cheddar.isSelected()){
            pastel += " + cheddar"; 
            subtotal+= 1 ;
        }
        
        if (jCheckBox_tomate.isSelected()){
            pastel += " + tomate"; 
         
        }
        if (jCheckBox_catupiry.isSelected()){
            pastel += " + catupiry"; 
            subtotal+= 1 ;
        }
        
        int qtd = Integer.parseInt(jTextField_qtd2.getText());
        item = "pastel" ;
     subtotal = subtotal * qtd ;
      add_list(item,tamanho,pastel, qtd,subtotal);
      PreencherTabela() ;
      total += subtotal ;
      subtotal = 0;
      jTextField_total.setText("R$ "+df.format(total));
      jTextField_qtd2.setText("1");
      
      
    }//GEN-LAST:event_jButton_add_pastel1ActionPerformed

    private void jComboBox_bebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_bebidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_bebidaActionPerformed

    private void jTextField_qtd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_qtd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_qtd1ActionPerformed

    private void jButton_add_bebida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_add_bebida1ActionPerformed
        bebida = (String) jComboBox_bebida.getSelectedItem();
       
        pesquisa_preco(bebida) ;
        int qtd = Integer.parseInt(jTextField_qtd1.getText());
        subtotal = valor_item * qtd;
        item="bebida" ;
        tamanho = "-";
        add_list(item,tamanho,bebida,qtd,subtotal);
        PreencherTabela() ;
        total += subtotal ;
         subtotal = 0;
         jTextField_total.setText("R$ "+df.format(total));
        jTextField_qtd1.setText("1");
        
        
    }//GEN-LAST:event_jButton_add_bebida1ActionPerformed

    private void jRadioButton_entregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_entregaActionPerformed
        if (jRadioButton_entrega.isSelected())
            jRadioButton_retirada.setSelected(false);
            
       if (jRadioButton_entrega.isSelected() && entrega == false){
          total += 2; 
          entrega = true ;
          tipo = "entrega" ;
        jTextField_total.setText("R$ "+df.format(total));
       }        
    }//GEN-LAST:event_jRadioButton_entregaActionPerformed

    private void jRadioButton_retiradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_retiradaActionPerformed
        if (jRadioButton_retirada.isSelected())
            jRadioButton_entrega.setSelected(false);
            
        if (entrega == true){
            entrega = false ;
            total-= 2;
            tipo = "retirada";
            DecimalFormat df = new DecimalFormat("##,###0.00"); 
        jTextField_total.setText("R$ "+df.format(total));
        }
            
        
    }//GEN-LAST:event_jRadioButton_retiradaActionPerformed

    private void jTextField_qtd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_qtd2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_qtd2ActionPerformed

    private void jFormattedText_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedText_dataActionPerformed

    }//GEN-LAST:event_jFormattedText_dataActionPerformed

    private void jButton_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salvarActionPerformed


    }
     
 public void insere_comanda(){
     String nome, data, rua, pag, taxa = null;
     int id ;
     double total ;
     
     if(entrega){
         taxa = "entrega";
     }else
         if(entrega == false)
             taxa = "retirada" ;
     
     nome = jTextField_nome.getText();
     data = jFormattedText_data.getText();
     rua = jTextField_ende.getText();
     id = Integer.parseInt(jTextField_id.getText());
     total = Double.parseDouble(jTextField_ende.getText());
     
     
     try {  // Insere o valor total da venda e o lucro no banco.
        PreparedStatement pst = conecta.conn.prepareStatement("insert into comanda (nome_cliente,ende,dia, entrega,total,id) values ('"+nome+"','"+rua+"','"+data+"','"+taxa+"',"+total+","+id+")");
        pst.execute();
        
       // JOptionPane.showMessageDialog(null,"inserido com sucesso");
    } catch (SQLException ex) {
        Logger.getLogger(Tela_inserirComanda.class.getName()).log(Level.SEVERE, null, ex);
    }
 }    //39834
    public double pesquisa_preco(String item){
      String tipo ;
        System.out.println("item funcao = "+ item);
        conecta.executaSQL("select * from cardapio where nome = '"+item+"'");
        
        try {
            
            conecta.rs.first();
            valor_item = conecta.rs.getDouble("pv") ;
            System.out.println("pv= "+ valor_item);
            
           tipo = conecta.rs.getString("tipo") ;
            System.out.println("tipo "+ tipo );
           
            
            System.out.println("subtotal dentro da função "+ subtotal);
        
        }catch (SQLException ex) {
          
         JOptionPane.showMessageDialog(null,"erro ao preencher"+ ex);
        
        }
   
        return valor_item ;
    }
        public void combox1(){
            
        
        jComboBox_sabor3.addItem("escolher");
        jComboBox_sabor4.addItem("escolher");
        jComboBox_bebida.addItem("escolher");
        
        
        try {
            conecta.executaSQL("select (nome) from cardapio where tipo = 'Pastel'");

            conecta.rs.first();
        
        do{
           jComboBox_sabor3.addItem(conecta.rs.getString("nome"));
           jComboBox_sabor4.addItem(conecta.rs.getString("nome"));
        }while(conecta.rs.next());
        }catch (SQLException ex) {
          
        //  JOptionPane.showMessageDialog(null,"erro ao preencher"+ ex);
        
        }
        conecta.executaSQL("select (nome) from cardapio where tipo = 'Bebida'");
        try {
            conecta.rs.first();
        
        do{
           jComboBox_bebida.addItem(conecta.rs.getString("nome"));
           
        }while(conecta.rs.next());
        }catch (SQLException ex) {
          
        //  JOptionPane.showMessageDialog(null,"erro ao preencher"+ ex);
        
        }
    
    }
  
   public void add_list(String item, String desc, String tam, int qtd, double sub){
       try {  // Insere o valor total da venda e o lucro no banco.
        PreparedStatement pst = conecta.conn.prepareStatement("insert into item_pedido (item,tam,descricao,qtd,subtotal) values ('"+item+"','"+tam+"','"+desc+"',"+qtd+","+sub+")");
        pst.execute();
        
       // JOptionPane.showMessageDialog(null,"inserido com sucesso");
    } catch (SQLException ex) {
        Logger.getLogger(Tela_inserirComanda.class.getName()).log(Level.SEVERE, null, ex);
    }
   }   
   
   public void del_list(){
     try {  
        PreparedStatement pst = conecta.conn.prepareStatement("delete from item_pedido");
        pst.execute();
        
       // JOptionPane.showMessageDialog(null,"inserido com sucesso");
    } catch (SQLException ex) {
        Logger.getLogger(Tela_inserirComanda.class.getName()).log(Level.SEVERE, null, ex);
    }  
   }
     
   public void PreencherTabela(){
        String produto, desc, tam;
         double sub ;
         int qtd ;
        
       ArrayList dados = new ArrayList();
        
        String [] Colunas = new String[]{"item","tamanho","descrição","quantidade","subtotal"};
           
        
        conecta.executaSQL("select * from item_pedido");
           try {
            conecta.rs.first();
       
         do{
            produto = conecta. rs.getString("item");
            tam = conecta. rs.getString("tam");
            desc = conecta. rs.getString("descricao");
            sub = conecta. rs.getDouble("subtotal");
            qtd = conecta. rs.getInt("qtd");
            
               System.out.println(item+desc+sub+qtd);
            
             DecimalFormat df = new DecimalFormat("##,###0.00"); 
           DecimalFormat df1 = new DecimalFormat("##,###0.00"); 
           
         dados.add(new Object[]{produto,desc,tam,qtd,"R$ "+df.format(sub)});
        
           }while(conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"erro ao preencher"+ ex);
        }
        
            
             
       
                
     ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTable_venda.setModel(modelo);
        jTable_venda.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTable_venda.getColumnModel().getColumn(0).setResizable(false);
        jTable_venda.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTable_venda.getColumnModel().getColumn(1).setResizable(false);
        jTable_venda.getColumnModel().getColumn(2).setPreferredWidth(510);
        jTable_venda.getColumnModel().getColumn(2).setResizable(false);
        jTable_venda.getColumnModel().getColumn(3).setPreferredWidth(90);
        jTable_venda.getColumnModel().getColumn(3).setResizable(false);
        jTable_venda.getColumnModel().getColumn(4).setPreferredWidth(150);
        jTable_venda.getColumnModel().getColumn(4).setResizable(false);

     
        
        jTable_venda.getTableHeader().setReorderingAllowed(false);
        jTable_venda.setAutoResizeMode(jTable_venda.AUTO_RESIZE_OFF);
        jTable_venda.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_inserirComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_inserirComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_inserirComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_inserirComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_inserirComanda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_add_bebida1;
    private javax.swing.JButton jButton_add_pastel1;
    private javax.swing.JButton jButton_salvar;
    private javax.swing.JCheckBox jCheckBox_azeitona;
    private javax.swing.JCheckBox jCheckBox_bacon;
    private javax.swing.JCheckBox jCheckBox_catupiry;
    private javax.swing.JCheckBox jCheckBox_cheddar;
    private javax.swing.JCheckBox jCheckBox_milho;
    private javax.swing.JCheckBox jCheckBox_ovos;
    private javax.swing.JCheckBox jCheckBox_tomate;
    private javax.swing.JComboBox<String> jComboBox_bebida;
    private javax.swing.JComboBox<String> jComboBox_dividido1;
    private javax.swing.JComboBox<String> jComboBox_dividido2;
    private javax.swing.JComboBox<String> jComboBox_dividido3;
    private javax.swing.JComboBox<String> jComboBox_integral;
    private javax.swing.JComboBox<String> jComboBox_sabor3;
    private javax.swing.JComboBox<String> jComboBox_sabor4;
    private javax.swing.JFormattedTextField jFormattedText_data;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton_20cm;
    private javax.swing.JRadioButton jRadioButton_30cm;
    private javax.swing.JRadioButton jRadioButton_entrega;
    private javax.swing.JRadioButton jRadioButton_retirada;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable_venda;
    private javax.swing.JTextField jTextField_ende;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_nome;
    private javax.swing.JTextField jTextField_pag1;
    private javax.swing.JTextField jTextField_pag2;
    private javax.swing.JTextField jTextField_pag3;
    private javax.swing.JTextField jTextField_qtd1;
    private javax.swing.JTextField jTextField_qtd2;
    private javax.swing.JTextField jTextField_total;
    // End of variables declaration//GEN-END:variables
}
